version: "3.9"
services:
  frontend:
    build: ../chsystem-frontend
    image: "chsystem-frontend:1.0"
    ports:
      - "4200:80"
  backend:
    build: .
    image: chsystem:1.0
    command:
      - "--spring.profiles.active=docker"
    volumes:
      - "/Users/b/dbs/chsystem_prod:/dbs"
    ports:
      - "8080:8080"

